openapi: 3.0.3
info:
  title: WASAPhoto
  description: |
    Keep in touch with your friends by sharing photos of special moments, thanks to WASAPhoto!  
    You can upload your photos directly from your PC, and they will be visible to everyone following you
  version: 0.1.0
servers:
  - url: http://localhost:3000

tags:
  - name: "MyProfile"
    description: "All about your Profile"
  - name: "ManageProfile"
    description: "Interact with Profiles"
  - name: "ManagePost"
    description: "All about your Post"

paths:
  /session:
    put:
      tags: ["MyProfile"]
      summary: Log in the user
      description: |-
        If the username does not exist, it will create a new profile.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema: {$ref: "#/components/schemas/Username"}
        required: true
      responses:
        '200':
          description: Log-in successfully
          content:
            application/json:
              schema: {$ref: "#/components/schemas/ID"}
        '201':
          description: Profile created
          content:
            application/json:
              schema: {$ref: "#/components/schemas/ID"}
        '400': { $ref: "#/components/responses/400BadRequest" }
        '500': { $ref: "#/components/responses/500InternalServerError" }


  /stream:
    get:
      security:
        - bearerAuth: []
      tags: ["MyProfile"]
      operationId: getMyStream
      summary: Get user's stream
      description: |
        The stream is composed by photos from “following” (other users that the user follows).
      responses:
        '200':
          description: User stream successfully found
          content:
            application/json:
              schema: {$ref: "#/components/schemas/Stream"}
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '500': {$ref: "#/components/responses/500InternalServerError"}

  /users/{UID}/profile:
    parameters:
      - $ref: "#/components/parameters/UserID"
    get:
      security:
        - bearerAuth: []
      tags: ["ManageProfile"]
      operationId:  getUserProfile
      summary: Search by username
      description: Get the profile of the user with the given one username in the request.
      responses:
        '200':
          description: User profile successfully found
          content:
            application/json:
              schema: {$ref: "#/components/schemas/UserProfile"}
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}
        '500': {$ref: "#/components/responses/500InternalServerError"}

  /profile/setUserName:
    put:
      security:
        - bearerAuth: []
      tags: ["MyProfile"]
      operationId: setMyUserName
      summary: Change username
      description: Set a new username for the current user.
      requestBody:
        description: User details
        content:
          application/json:
            schema: {$ref: "#/components/schemas/Username"}
        required: true
      responses:
        '204':
          description: Name successfully changed
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '500': {$ref: "#/components/responses/500InternalServerError"}

  /users/{UID}/follow:
    parameters:
      - $ref: "#/components/parameters/UserID"
    put:
      security:
        - bearerAuth: []
      tags: ["ManageProfile"]
      operationId: followUser
      summary: Follow an user
      description: Follow an user if it's not followed yet.
      responses:
        '204':
          description: User successfully followed
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
    delete:
      security:
        - bearerAuth: []
      tags: ["ManageProfile"]
      operationId: unfollowUser
      summary: Unfollow an user
      description: Unfollow an user if it's already followed.
      responses:
        '204':
          description: User successfully unfollowed
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}

  /users/{UID}/ban:
    parameters:
      - $ref: "#/components/parameters/UserID"
    put:
      security:
        - bearerAuth: []
      tags: ["ManageProfile"]
      operationId: banUser
      summary: Ban an user
      description: Ban an user if it's not banned yet.
      responses:
        '204':
          description: User successfully banned
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}
    delete:
      security:
        - bearerAuth: []
      tags: ["ManageProfile"]
      operationId: unbanUser
      summary: Unban an user
      description: Unban an user if it's already banned.
      responses:
        '204':
          description: User successfully unbanned
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}

  /posts:
    post:
      security:
        - bearerAuth: []
      tags: ["ManageProfile"]
      operationId: uploadPhoto
      summary: Upload a photo
      description: Upload a photo on the profile.
      requestBody:
        description: Photo details
        content:
          multipart/form-data:
            schema:
              description: Request for photo image and photo description.
              type: object
              properties:
                Photo: {$ref: "#/components/schemas/Post/properties/File"}
                Description: {$ref: "#/components/schemas/Post/properties/Description"}
        required: true
      responses:
        '201':
          description: Photo successfully uploaded
          content:
            application/json:
              schema: {$ref: "#/components/schemas/ID"}
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}
        '500': {$ref: "#/components/responses/500InternalServerError"}

  /posts/{postID}:
    parameters:
      - $ref: "#/components/parameters/PostID"
    get:
      security:
        - bearerAuth: [ ]
      tags: [ "ManageProfile" ]
      operationId: getFullPost
      summary: Get Post info
      description: Get post's info with it's like and comments
      responses:
        '200':
          description: Post successfully found
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Post" }
        '400': { $ref: "#/components/responses/400BadRequest" }
        '401': { $ref: "#/components/responses/401UnauthorizedError" }
        '404': { $ref: "#/components/responses/404NotFound" }
        '500': { $ref: "#/components/responses/500InternalServerError" }

    delete:
      security:
        - bearerAuth: []
      tags: ["ManageProfile"]
      operationId: deletePhoto
      summary: Delete a photo
      description: |
        Delete a photo from the profile.

        Removal of an image will also remove likes and comments.
      responses:
        '204':
          description: Photo successfully deleted
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}

  /posts/{postID}/likes:
    parameters:
      - $ref: "#/components/parameters/PostID"
    put:
      security:
        - bearerAuth: []
      tags: ["ManagePost"]
      operationId: likePhoto
      summary: Like a Photo
      description: Like a post if it's not liked yet.
      responses:
        '204':
          description: Photo successfully liked
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}

    delete:
      security:
        - bearerAuth: []
      tags: ["ManagePost"]
      operationId: unlikePhoto
      summary: Unlike a Photo
      description: Remove like from a photo if it's already liked.
      responses:
        '204':
          description: Photo successfully unliked
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}

  /posts/{postID}/comments:
    parameters:
      - $ref: "#/components/parameters/PostID"
    post:
      security:
        - bearerAuth: []
      tags: ["ManagePost"]
      operationId: commentPhoto
      summary: Comment a photo
      description: Public a comment about a post.
      requestBody:
        description: Comment details
        content:
          application/json:
            schema: {$ref: '#/components/schemas/Text'}
        required: true
      responses:
        '201':
          description: Comment successfully created
          content:
            application/json:
              schema: {$ref: "#/components/schemas/ID"}
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}
        '500': {$ref: "#/components/responses/500InternalServerError"}

  /posts/{postID}/comments/{commentID}:
    parameters:
      - $ref: "#/components/parameters/PostID"
      - $ref: "#/components/parameters/CommentID"
    delete:
      security:
        - bearerAuth: []
      tags: ["ManagePost"]
      operationId: uncommentPhoto
      summary: Delete a comment
      description: |
        Delete a comment from a post. 
        
        Only authors can remove their comments.
      responses:
        '204':
          description: Photo successfully uncommented
        '400': {$ref: "#/components/responses/400BadRequest"}
        '401': {$ref: "#/components/responses/401UnauthorizedError"}
        '404': {$ref: "#/components/responses/404NotFound"}



components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    400BadRequest:
      description: The request was not compliant with the documnetation (eg. missing field, etc).
    401UnauthorizedError:
      description: Unauthorised, the user does not have valid authentication credentials for the target resource.
    404NotFound:
      description: The requested resource could not be found but may be available in the future.
    500InternalServerError:
      description: Server sIDe error.

  parameters:
    UserID:
      name: UID
      description: User identifier
      schema: {$ref: "#/components/schemas/ID"}
      in: path
      required: true
    PostID:
      name: postID
      description: Post identifier
      schema: {$ref: "#/components/schemas/ID"}
      in: path
      required: true
    CommentID:
      name: commentID
      description: Comment identifier
      schema: {$ref: "#/components/schemas/ID"}
      in: path
      required: true


  schemas:
    Stream:
      description: User stream schema
      type: object
      properties:
        Posts: {$ref: "#/components/schemas/ListOfPosts"}

    Profile:
      description: |
        A profile contains an user's photos (in reverse chronological order),
        how many photos have been uploaded, and the user's followers and
        following.
      type: object
      properties:
        ID: {$ref: "#/components/schemas/ID"}
        Username: {$ref: "#/components/schemas/Username"}
        FollowersCount: {$ref: "#/components/schemas/Count"}
        FollowingCount: {$ref: "#/components/schemas/Count"}
        PostsCount: {$ref: "#/components/schemas/Count"}

    UserProfile:
      description: A profile with relative information schema
      type: object
      properties:
        Profile: {$ref: "#/components/schemas/Profile"}
        Posts: {$ref: "#/components/schemas/ListOfPosts"}
        Followings: {$ref: "#/components/schemas/ListOfID"}
        Followers: {$ref: "#/components/schemas/ListOfID"}

    Post:
      description: Post schema
      type: object
      properties:
        ID: {$ref: "#/components/schemas/ID"}
        ProfileID: {$ref: "#/components/schemas/Profile/properties/ID"}
        File:
          description: Photo
          type: string
          format: binary
          minLength: 0
          maxLength: 1048576
        Description: {$ref: "#/components/schemas/Text"}
        LikesCount: {$ref: "#/components/schemas/Count"}
        CommentsCount: {$ref: "#/components/schemas/Count"}
        DateTime: {$ref: "#/components/schemas/DateTime"}

    ID:
      description: ID schema
      type: integer
      minimum: 1
      example: 1993737
      readOnly: true

    Username:
      description: Username schema
      type: object
      properties:
        Name:
          description: Name schema
          type: string
          example: Eve
          pattern: '^.*?$'
          minLength: 3
          maxLength: 16

    Text:
      description: Text schema
      type: string
      pattern: '^.*?$'
      minLength: 0
      maxLength: 150
      example: This is a text
    
    Count:
      description: Counter schema
      type: integer
      minimum: 0
      example: 24
    
    DateTime:
      description: Date and time schema
      type: string
      format: date-time
      example: 2023-11-06T14:38:28Z

    ListOfPosts:
      description: List of posts schema
      type: array
      items: {$ref: "#/components/schemas/Post"}
      minItems: 0
      maxItems: 9999
      uniqueItems: true

    ListOfID:
      description: List of ID schema
      type: array
      items: { $ref: "#/components/schemas/ID" }
      minItems: 0
      maxItems: 9999
      uniqueItems: true